/* eslint-disable */
/* tslint:disable */
// noinspection JSUnusedGlobalSymbols
// biome-ignore-all
/*
 * ------------------------------------------------------------
 * ## This file was automatically generated by drizzle-zero. ##
 * ## Any changes you make to this file will be overwritten. ##
 * ##                                                        ##
 * ## Additionally, you should also exclude this file from   ##
 * ## your linter and/or formatter to prevent it from being  ##
 * ## checked or modified.                                   ##
 * ##                                                        ##
 * ## SOURCE: https://github.com/0xcadams/drizzle-zero        ##
 * ------------------------------------------------------------
 */

import type { Row } from "@rocicorp/zero";
import { createBuilder } from "@rocicorp/zero";
import type { DrizzleToZeroSchema, ZeroCustomType } from "drizzle-zero";
import type * as drizzleSchema from "./app/db/schema";

type ZeroSchema = DrizzleToZeroSchema<typeof drizzleSchema>;

/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    attachmentsTable: {
      name: "attachmentsTable",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "attachmentsTable",
            "id"
          >,
        },
        message_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "attachmentsTable",
            "message_id"
          >,
        },
        filename: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "attachmentsTable",
            "filename"
          >,
        },
        file_type: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "attachmentsTable",
            "file_type"
          >,
        },
        file_size: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "attachmentsTable",
            "file_size"
          >,
        },
        storage_path: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "attachmentsTable",
            "storage_path"
          >,
        },
        created_at: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "attachmentsTable",
            "created_at"
          >,
        },
      },
      primaryKey: ["id"],
      serverName: "attachments",
    },
    channelGithubIntegrationsTable: {
      name: "channelGithubIntegrationsTable",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelGithubIntegrationsTable",
            "id"
          >,
        },
        channel_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelGithubIntegrationsTable",
            "channel_id"
          >,
        },
        repo_owner: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelGithubIntegrationsTable",
            "repo_owner"
          >,
        },
        repo_name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelGithubIntegrationsTable",
            "repo_name"
          >,
        },
        access_token: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelGithubIntegrationsTable",
            "access_token"
          >,
        },
        connected_by: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelGithubIntegrationsTable",
            "connected_by"
          >,
        },
        created_at: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelGithubIntegrationsTable",
            "created_at"
          >,
        },
      },
      primaryKey: ["id"],
      serverName: "channel_github_integrations",
    },
    channelGitlabIntegrationsTable: {
      name: "channelGitlabIntegrationsTable",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelGitlabIntegrationsTable",
            "id"
          >,
        },
        channel_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelGitlabIntegrationsTable",
            "channel_id"
          >,
        },
        project_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelGitlabIntegrationsTable",
            "project_id"
          >,
        },
        project_path: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelGitlabIntegrationsTable",
            "project_path"
          >,
        },
        access_token: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelGitlabIntegrationsTable",
            "access_token"
          >,
        },
        connected_by: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelGitlabIntegrationsTable",
            "connected_by"
          >,
        },
        created_at: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelGitlabIntegrationsTable",
            "created_at"
          >,
        },
      },
      primaryKey: ["id"],
      serverName: "channel_gitlab_integrations",
    },
    channelGroupAccess: {
      name: "channelGroupAccess",
      columns: {
        channel_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelGroupAccess",
            "channel_id"
          >,
        },
        group_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelGroupAccess",
            "group_id"
          >,
        },
        can_write: {
          type: "boolean",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelGroupAccess",
            "can_write"
          >,
        },
      },
      primaryKey: ["channel_id", "group_id"],
      serverName: "channel_group_access",
    },
    channelMembers: {
      name: "channelMembers",
      columns: {
        userId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelMembers",
            "userId"
          >,
          serverName: "user_id",
        },
        channelId: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelMembers",
            "channelId"
          >,
          serverName: "channel_id",
        },
        role: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelMembers",
            "role"
          >,
        },
      },
      primaryKey: ["userId", "channelId"],
      serverName: "channel_members",
    },
    channelUserAccess: {
      name: "channelUserAccess",
      columns: {
        channel_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelUserAccess",
            "channel_id"
          >,
        },
        user_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelUserAccess",
            "user_id"
          >,
        },
        can_write: {
          type: "boolean",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelUserAccess",
            "can_write"
          >,
        },
      },
      primaryKey: ["channel_id", "user_id"],
      serverName: "channel_user_access",
    },
    channelWebhooksTable: {
      name: "channelWebhooksTable",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelWebhooksTable",
            "id"
          >,
        },
        channel_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelWebhooksTable",
            "channel_id"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelWebhooksTable",
            "name"
          >,
        },
        token_hash: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelWebhooksTable",
            "token_hash"
          >,
        },
        created_by: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelWebhooksTable",
            "created_by"
          >,
        },
        created_at: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelWebhooksTable",
            "created_at"
          >,
        },
        last_used_at: {
          type: "number",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelWebhooksTable",
            "last_used_at"
          >,
        },
      },
      primaryKey: ["id"],
      serverName: "channel_webhooks",
    },
    channelsTable: {
      name: "channelsTable",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelsTable",
            "id"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelsTable",
            "name"
          >,
        },
        created_at: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelsTable",
            "created_at"
          >,
        },
        owner_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelsTable",
            "owner_id"
          >,
        },
        is_private: {
          type: "boolean",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "channelsTable",
            "is_private"
          >,
        },
      },
      primaryKey: ["id"],
      serverName: "channels",
    },
    groupMembers: {
      name: "groupMembers",
      columns: {
        group_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "groupMembers",
            "group_id"
          >,
        },
        user_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "groupMembers",
            "user_id"
          >,
        },
      },
      primaryKey: ["group_id", "user_id"],
      serverName: "group_members",
    },
    groupsTable: {
      name: "groupsTable",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "groupsTable",
            "id"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "groupsTable",
            "name"
          >,
        },
        owner_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "groupsTable",
            "owner_id"
          >,
        },
        created_at: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "groupsTable",
            "created_at"
          >,
        },
      },
      primaryKey: ["id"],
      serverName: "groups",
    },
    messagesTable: {
      name: "messagesTable",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messagesTable",
            "id"
          >,
        },
        content: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messagesTable",
            "content"
          >,
        },
        created_at: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messagesTable",
            "created_at"
          >,
        },
        author_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messagesTable",
            "author_id"
          >,
        },
        channel_id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messagesTable",
            "channel_id"
          >,
        },
        direct_to_id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messagesTable",
            "direct_to_id"
          >,
        },
        parent_id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messagesTable",
            "parent_id"
          >,
        },
        updated: {
          type: "boolean",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messagesTable",
            "updated"
          >,
        },
        webhook_id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "messagesTable",
            "webhook_id"
          >,
        },
      },
      primaryKey: ["id"],
      serverName: "messages",
    },
    notificationsTable: {
      name: "notificationsTable",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "notificationsTable",
            "id"
          >,
        },
        user_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "notificationsTable",
            "user_id"
          >,
        },
        message_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "notificationsTable",
            "message_id"
          >,
        },
        channel_id: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "notificationsTable",
            "channel_id"
          >,
        },
        mention_type: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "notificationsTable",
            "mention_type"
          >,
        },
        is_read: {
          type: "boolean",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "notificationsTable",
            "is_read"
          >,
        },
        created_at: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "notificationsTable",
            "created_at"
          >,
        },
      },
      primaryKey: ["id"],
      serverName: "notifications",
    },
    reactionsTable: {
      name: "reactionsTable",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "reactionsTable",
            "id"
          >,
        },
        message_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "reactionsTable",
            "message_id"
          >,
        },
        user_id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "reactionsTable",
            "user_id"
          >,
        },
        reaction: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "reactionsTable",
            "reaction"
          >,
        },
        created_at: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "reactionsTable",
            "created_at"
          >,
        },
      },
      primaryKey: ["id"],
      serverName: "reactions",
    },
    usersTable: {
      name: "usersTable",
      columns: {
        id: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "usersTable",
            "id"
          >,
        },
        name: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "usersTable",
            "name"
          >,
        },
        email: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "usersTable",
            "email"
          >,
        },
        image: {
          type: "string",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "usersTable",
            "image"
          >,
        },
        role: {
          type: "string",
          optional: true,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "usersTable",
            "role"
          >,
        },
        created_at: {
          type: "number",
          optional: false,
          customType: null as unknown as ZeroCustomType<
            ZeroSchema,
            "usersTable",
            "created_at"
          >,
        },
      },
      primaryKey: ["id"],
      serverName: "users",
    },
  },
  relationships: {
    attachmentsTable: {
      message: [
        {
          sourceField: ["message_id"],
          destField: ["id"],
          destSchema: "messagesTable",
          cardinality: "one",
        },
      ],
    },
    channelGithubIntegrationsTable: {
      channel: [
        {
          sourceField: ["channel_id"],
          destField: ["id"],
          destSchema: "channelsTable",
          cardinality: "one",
        },
      ],
      connectedBy: [
        {
          sourceField: ["connected_by"],
          destField: ["id"],
          destSchema: "usersTable",
          cardinality: "one",
        },
      ],
    },
    channelGitlabIntegrationsTable: {
      channel: [
        {
          sourceField: ["channel_id"],
          destField: ["id"],
          destSchema: "channelsTable",
          cardinality: "one",
        },
      ],
      connectedBy: [
        {
          sourceField: ["connected_by"],
          destField: ["id"],
          destSchema: "usersTable",
          cardinality: "one",
        },
      ],
    },
    channelGroupAccess: {
      channel: [
        {
          sourceField: ["channel_id"],
          destField: ["id"],
          destSchema: "channelsTable",
          cardinality: "one",
        },
      ],
      group: [
        {
          sourceField: ["group_id"],
          destField: ["id"],
          destSchema: "groupsTable",
          cardinality: "one",
        },
      ],
    },
    channelMembers: {
      user: [
        {
          sourceField: ["userId"],
          destField: ["id"],
          destSchema: "usersTable",
          cardinality: "one",
        },
      ],
      channel: [
        {
          sourceField: ["channelId"],
          destField: ["id"],
          destSchema: "channelsTable",
          cardinality: "one",
        },
      ],
    },
    channelUserAccess: {
      channel: [
        {
          sourceField: ["channel_id"],
          destField: ["id"],
          destSchema: "channelsTable",
          cardinality: "one",
        },
      ],
      user: [
        {
          sourceField: ["user_id"],
          destField: ["id"],
          destSchema: "usersTable",
          cardinality: "one",
        },
      ],
    },
    channelWebhooksTable: {
      channel: [
        {
          sourceField: ["channel_id"],
          destField: ["id"],
          destSchema: "channelsTable",
          cardinality: "one",
        },
      ],
      createdBy: [
        {
          sourceField: ["created_by"],
          destField: ["id"],
          destSchema: "usersTable",
          cardinality: "one",
        },
      ],
      messages: [
        {
          sourceField: ["id"],
          destField: ["webhook_id"],
          destSchema: "messagesTable",
          cardinality: "many",
        },
      ],
    },
    channelsTable: {
      messages: [
        {
          sourceField: ["id"],
          destField: ["channel_id"],
          destSchema: "messagesTable",
          cardinality: "many",
        },
      ],
      members: [
        {
          sourceField: ["id"],
          destField: ["channelId"],
          destSchema: "channelMembers",
          cardinality: "many",
        },
      ],
      userAccess: [
        {
          sourceField: ["id"],
          destField: ["channel_id"],
          destSchema: "channelUserAccess",
          cardinality: "many",
        },
      ],
      groupAccess: [
        {
          sourceField: ["id"],
          destField: ["channel_id"],
          destSchema: "channelGroupAccess",
          cardinality: "many",
        },
      ],
      githubIntegrations: [
        {
          sourceField: ["id"],
          destField: ["channel_id"],
          destSchema: "channelGithubIntegrationsTable",
          cardinality: "many",
        },
      ],
      gitlabIntegrations: [
        {
          sourceField: ["id"],
          destField: ["channel_id"],
          destSchema: "channelGitlabIntegrationsTable",
          cardinality: "many",
        },
      ],
      owner: [
        {
          sourceField: ["owner_id"],
          destField: ["id"],
          destSchema: "usersTable",
          cardinality: "one",
        },
      ],
    },
    groupMembers: {
      group: [
        {
          sourceField: ["group_id"],
          destField: ["id"],
          destSchema: "groupsTable",
          cardinality: "one",
        },
      ],
      user: [
        {
          sourceField: ["user_id"],
          destField: ["id"],
          destSchema: "usersTable",
          cardinality: "one",
        },
      ],
    },
    groupsTable: {
      members: [
        {
          sourceField: ["id"],
          destField: ["group_id"],
          destSchema: "groupMembers",
          cardinality: "many",
        },
      ],
      channelAccess: [
        {
          sourceField: ["id"],
          destField: ["group_id"],
          destSchema: "channelGroupAccess",
          cardinality: "many",
        },
      ],
      owner: [
        {
          sourceField: ["owner_id"],
          destField: ["id"],
          destSchema: "usersTable",
          cardinality: "one",
        },
      ],
    },
    messagesTable: {
      author: [
        {
          sourceField: ["author_id"],
          destField: ["id"],
          destSchema: "usersTable",
          cardinality: "one",
        },
      ],
      channel: [
        {
          sourceField: ["channel_id"],
          destField: ["id"],
          destSchema: "channelsTable",
          cardinality: "one",
        },
      ],
      direct_to: [
        {
          sourceField: ["direct_to_id"],
          destField: ["id"],
          destSchema: "usersTable",
          cardinality: "one",
        },
      ],
      parent: [
        {
          sourceField: ["parent_id"],
          destField: ["id"],
          destSchema: "messagesTable",
          cardinality: "one",
        },
      ],
      webhook: [
        {
          sourceField: ["webhook_id"],
          destField: ["id"],
          destSchema: "channelWebhooksTable",
          cardinality: "one",
        },
      ],
      reactions: [
        {
          sourceField: ["id"],
          destField: ["message_id"],
          destSchema: "reactionsTable",
          cardinality: "many",
        },
      ],
      attachments: [
        {
          sourceField: ["id"],
          destField: ["message_id"],
          destSchema: "attachmentsTable",
          cardinality: "many",
        },
      ],
      replies: [
        {
          sourceField: ["id"],
          destField: ["parent_id"],
          destSchema: "messagesTable",
          cardinality: "many",
        },
      ],
      notifications: [
        {
          sourceField: ["id"],
          destField: ["message_id"],
          destSchema: "notificationsTable",
          cardinality: "many",
        },
      ],
    },
    notificationsTable: {
      user: [
        {
          sourceField: ["user_id"],
          destField: ["id"],
          destSchema: "usersTable",
          cardinality: "one",
        },
      ],
      message: [
        {
          sourceField: ["message_id"],
          destField: ["id"],
          destSchema: "messagesTable",
          cardinality: "one",
        },
      ],
      channel: [
        {
          sourceField: ["channel_id"],
          destField: ["id"],
          destSchema: "channelsTable",
          cardinality: "one",
        },
      ],
    },
    reactionsTable: {
      message: [
        {
          sourceField: ["message_id"],
          destField: ["id"],
          destSchema: "messagesTable",
          cardinality: "one",
        },
      ],
      user: [
        {
          sourceField: ["user_id"],
          destField: ["id"],
          destSchema: "usersTable",
          cardinality: "one",
        },
      ],
    },
    usersTable: {
      author: [
        {
          sourceField: ["id"],
          destField: ["author_id"],
          destSchema: "messagesTable",
          cardinality: "many",
        },
      ],
      sent_direct_messages: [
        {
          sourceField: ["id"],
          destField: ["direct_to_id"],
          destSchema: "messagesTable",
          cardinality: "many",
        },
      ],
      members: [
        {
          sourceField: ["id"],
          destField: ["userId"],
          destSchema: "channelMembers",
          cardinality: "many",
        },
      ],
      ownedChannels: [
        {
          sourceField: ["id"],
          destField: ["owner_id"],
          destSchema: "channelsTable",
          cardinality: "many",
        },
      ],
      ownedGroups: [
        {
          sourceField: ["id"],
          destField: ["owner_id"],
          destSchema: "groupsTable",
          cardinality: "many",
        },
      ],
      groupMemberships: [
        {
          sourceField: ["id"],
          destField: ["user_id"],
          destSchema: "groupMembers",
          cardinality: "many",
        },
      ],
      channelAccess: [
        {
          sourceField: ["id"],
          destField: ["user_id"],
          destSchema: "channelUserAccess",
          cardinality: "many",
        },
      ],
      notifications: [
        {
          sourceField: ["id"],
          destField: ["user_id"],
          destSchema: "notificationsTable",
          cardinality: "many",
        },
      ],
    },
  },
  enableLegacyQueries: true,
  enableLegacyMutators: true,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
/**
 * Represents a row from the "attachmentsTable" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type AttachmentsTable = Row<Schema["tables"]["attachmentsTable"]>;
/**
 * Represents a row from the "channelGithubIntegrationsTable" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ChannelGithubIntegrationsTable = Row<
  Schema["tables"]["channelGithubIntegrationsTable"]
>;
/**
 * Represents a row from the "channelGitlabIntegrationsTable" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ChannelGitlabIntegrationsTable = Row<
  Schema["tables"]["channelGitlabIntegrationsTable"]
>;
/**
 * Represents a row from the "channelGroupAccess" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ChannelGroupAccess = Row<Schema["tables"]["channelGroupAccess"]>;
/**
 * Represents a row from the "channelMembers" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ChannelMember = Row<Schema["tables"]["channelMembers"]>;
/**
 * Represents a row from the "channelUserAccess" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ChannelUserAccess = Row<Schema["tables"]["channelUserAccess"]>;
/**
 * Represents a row from the "channelWebhooksTable" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ChannelWebhooksTable = Row<
  Schema["tables"]["channelWebhooksTable"]
>;
/**
 * Represents a row from the "channelsTable" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ChannelsTable = Row<Schema["tables"]["channelsTable"]>;
/**
 * Represents a row from the "groupMembers" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type GroupMember = Row<Schema["tables"]["groupMembers"]>;
/**
 * Represents a row from the "groupsTable" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type GroupsTable = Row<Schema["tables"]["groupsTable"]>;
/**
 * Represents a row from the "messagesTable" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type MessagesTable = Row<Schema["tables"]["messagesTable"]>;
/**
 * Represents a row from the "notificationsTable" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type NotificationsTable = Row<Schema["tables"]["notificationsTable"]>;
/**
 * Represents a row from the "reactionsTable" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type ReactionsTable = Row<Schema["tables"]["reactionsTable"]>;
/**
 * Represents a row from the "usersTable" table.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type UsersTable = Row<Schema["tables"]["usersTable"]>;

/**
 * Represents the Zero schema query builder.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const builder = createBuilder(schema);
